# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana_principal.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(422, 482)
        MainWindow.setMaximumSize(QtCore.QSize(422, 482))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app_cok.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.mainScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.mainScrollArea.setWidgetResizable(False)
        self.mainScrollArea.setObjectName("mainScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 420, 480))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainGroupBox.sizePolicy().hasHeightForWidth())
        self.mainGroupBox.setSizePolicy(sizePolicy)
        self.mainGroupBox.setMinimumSize(QtCore.QSize(420, 480))
        self.mainGroupBox.setMaximumSize(QtCore.QSize(420, 480))
        self.mainGroupBox.setTitle("")
        self.mainGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mainGroupBox.setFlat(False)
        self.mainGroupBox.setObjectName("mainGroupBox")
        self.spnbx_Nfarms = QtWidgets.QSpinBox(self.mainGroupBox)
        self.spnbx_Nfarms.setGeometry(QtCore.QRect(220, 10, 42, 22))
        self.spnbx_Nfarms.setMinimum(1)
        self.spnbx_Nfarms.setMaximum(100)
        self.spnbx_Nfarms.setObjectName("spnbx_Nfarms")
        self.lbl_Nfarms = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_Nfarms.setGeometry(QtCore.QRect(10, 10, 211, 22))
        self.lbl_Nfarms.setObjectName("lbl_Nfarms")
        self.lbl_position = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_position.setGeometry(QtCore.QRect(30, 50, 51, 40))
        self.lbl_position.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_position.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lbl_position.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_position.setObjectName("lbl_position")
        self.lbl_resource = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_resource.setGeometry(QtCore.QRect(85, 50, 51, 40))
        self.lbl_resource.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_resource.setObjectName("lbl_resource")
        self.scrollArea = QtWidgets.QScrollArea(self.mainGroupBox)
        self.scrollArea.setGeometry(QtCore.QRect(20, 90, 381, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 379, 319))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.farms_layout = QtWidgets.QGridLayout()
        self.farms_layout.setContentsMargins(0, -1, -1, -1)
        self.farms_layout.setHorizontalSpacing(6)
        self.farms_layout.setObjectName("farms_layout")
        self.cbx_resource1 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.cbx_resource1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.cbx_resource1.setObjectName("cbx_resource1")
        self.cbx_resource1.addItem("")
        self.cbx_resource1.addItem("")
        self.cbx_resource1.addItem("")
        self.cbx_resource1.addItem("")
        self.farms_layout.addWidget(self.cbx_resource1, 0, 1, 1, 1)
        self.chbx_heal1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chbx_heal1.setText("")
        self.chbx_heal1.setChecked(True)
        self.chbx_heal1.setObjectName("chbx_heal1")
        self.farms_layout.addWidget(self.chbx_heal1, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.chbx_donate1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chbx_donate1.setText("")
        self.chbx_donate1.setChecked(True)
        self.chbx_donate1.setObjectName("chbx_donate1")
        self.farms_layout.addWidget(self.chbx_donate1, 0, 6, 1, 1, QtCore.Qt.AlignHCenter)
        self.chbx_train1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chbx_train1.sizePolicy().hasHeightForWidth())
        self.chbx_train1.setSizePolicy(sizePolicy)
        self.chbx_train1.setText("")
        self.chbx_train1.setChecked(True)
        self.chbx_train1.setObjectName("chbx_train1")
        self.farms_layout.addWidget(self.chbx_train1, 0, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.cbx_position1 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.cbx_position1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cbx_position1.setObjectName("cbx_position1")
        self.cbx_position1.addItem("")
        self.farms_layout.addWidget(self.cbx_position1, 0, 0, 1, 1)
        self.spnbx_level1 = QtWidgets.QSpinBox(self.scrollAreaWidgetContents_2)
        self.spnbx_level1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.spnbx_level1.setMinimum(1)
        self.spnbx_level1.setMaximum(8)
        self.spnbx_level1.setProperty("value", 4)
        self.spnbx_level1.setObjectName("spnbx_level1")
        self.farms_layout.addWidget(self.spnbx_level1, 0, 2, 1, 1)
        self.chbx_gathersm1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.chbx_gathersm1.setText("")
        self.chbx_gathersm1.setChecked(True)
        self.chbx_gathersm1.setObjectName("chbx_gathersm1")
        self.farms_layout.addWidget(self.chbx_gathersm1, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_5.addLayout(self.farms_layout, 0, 0, 1, 1)
        self.lbl_to_fill_space_v = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_to_fill_space_v.sizePolicy().hasHeightForWidth())
        self.lbl_to_fill_space_v.setSizePolicy(sizePolicy)
        self.lbl_to_fill_space_v.setText("")
        self.lbl_to_fill_space_v.setObjectName("lbl_to_fill_space_v")
        self.gridLayout_5.addWidget(self.lbl_to_fill_space_v, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.lbl_train = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_train.setGeometry(QtCore.QRect(300, 50, 31, 40))
        self.lbl_train.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_train.setObjectName("lbl_train")
        self.lbl_resource_2 = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_resource_2.setGeometry(QtCore.QRect(340, 50, 51, 40))
        self.lbl_resource_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_resource_2.setObjectName("lbl_resource_2")
        self.lbl_heal = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_heal.setGeometry(QtCore.QRect(250, 50, 31, 40))
        self.lbl_heal.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_heal.setObjectName("lbl_heal")
        self.lbl_level = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_level.setGeometry(QtCore.QRect(145, 50, 31, 40))
        self.lbl_level.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_level.setObjectName("lbl_level")
        self.pbtn_start = QtWidgets.QPushButton(self.mainGroupBox)
        self.pbtn_start.setGeometry(QtCore.QRect(320, 430, 75, 23))
        self.pbtn_start.setObjectName("pbtn_start")
        self.lbl_correo_contacto = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_correo_contacto.setGeometry(QtCore.QRect(10, 450, 171, 20))
        self.lbl_correo_contacto.setObjectName("lbl_correo_contacto")
        self.pbtn_stop = QtWidgets.QPushButton(self.mainGroupBox)
        self.pbtn_stop.setGeometry(QtCore.QRect(320, 430, 75, 23))
        self.pbtn_stop.setObjectName("pbtn_stop")
        self.pbtn_how_to_use = QtWidgets.QPushButton(self.mainGroupBox)
        self.pbtn_how_to_use.setGeometry(QtCore.QRect(320, 10, 81, 23))
        self.pbtn_how_to_use.setObjectName("pbtn_how_to_use")
        self.lbl_heal_2 = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_heal_2.setGeometry(QtCore.QRect(185, 50, 51, 40))
        self.lbl_heal_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_heal_2.setObjectName("lbl_heal_2")
        self.lbl_prompt = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_prompt.setGeometry(QtCore.QRect(20, 420, 191, 21))
        self.lbl_prompt.setStyleSheet("color:green")
        self.lbl_prompt.setText("")
        self.lbl_prompt.setObjectName("lbl_prompt")
        self.lbl_crono = QtWidgets.QLabel(self.mainGroupBox)
        self.lbl_crono.setGeometry(QtCore.QRect(310, 455, 101, 20))
        self.lbl_crono.setStyleSheet("color:red")
        self.lbl_crono.setText("")
        self.lbl_crono.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_crono.setObjectName("lbl_crono")
        self.cbx_device = QtWidgets.QComboBox(self.mainGroupBox)
        self.cbx_device.setGeometry(QtCore.QRect(220, 430, 81, 23))
        self.cbx_device.setObjectName("cbx_device")
        self.cbx_device.addItem("")
        self.cbx_device.addItem("")
        self.pbtn_stop.raise_()
        self.spnbx_Nfarms.raise_()
        self.lbl_Nfarms.raise_()
        self.lbl_position.raise_()
        self.lbl_resource.raise_()
        self.scrollArea.raise_()
        self.lbl_train.raise_()
        self.lbl_resource_2.raise_()
        self.lbl_heal.raise_()
        self.lbl_level.raise_()
        self.pbtn_start.raise_()
        self.lbl_correo_contacto.raise_()
        self.pbtn_how_to_use.raise_()
        self.lbl_heal_2.raise_()
        self.lbl_prompt.raise_()
        self.lbl_crono.raise_()
        self.cbx_device.raise_()
        self.gridLayout_2.addWidget(self.mainGroupBox, 0, 0, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.mainScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.mainScrollArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aj COK Farming Bot"))
        self.lbl_Nfarms.setToolTip(_translate("MainWindow", "<html><head/><body><p>It takes the first accounts (from top to bottom) in the Google Play list.</p></body></html>"))
        self.lbl_Nfarms.setText(_translate("MainWindow", "Number of accounts in the Google Play list:"))
        self.lbl_position.setToolTip(_translate("MainWindow", "<html><head/><body><p>Position of the account in the Google Play list. The position 1 refers to the account allocated on the top of that list.</p></body></html>"))
        self.lbl_position.setText(_translate("MainWindow", "Account\n"
"position"))
        self.lbl_resource.setText(_translate("MainWindow", "Resource"))
        self.cbx_resource1.setItemText(0, _translate("MainWindow", "Food"))
        self.cbx_resource1.setItemText(1, _translate("MainWindow", "Wood"))
        self.cbx_resource1.setItemText(2, _translate("MainWindow", "Iron"))
        self.cbx_resource1.setItemText(3, _translate("MainWindow", "Mithril"))
        self.cbx_position1.setItemText(0, _translate("MainWindow", "1"))
        self.lbl_train.setText(_translate("MainWindow", "Train\n"
"troops"))
        self.lbl_resource_2.setText(_translate("MainWindow", "Donate\n"
"to alliance"))
        self.lbl_heal.setText(_translate("MainWindow", "Heal\n"
"troops"))
        self.lbl_level.setText(_translate("MainWindow", "Level"))
        self.pbtn_start.setText(_translate("MainWindow", "Start"))
        self.lbl_correo_contacto.setText(_translate("MainWindow", "contact.cokfarmingbot@gmail.com"))
        self.pbtn_stop.setText(_translate("MainWindow", "Stop"))
        self.pbtn_how_to_use.setText(_translate("MainWindow", "How to use"))
        self.lbl_heal_2.setText(_translate("MainWindow", "Gather\n"
"SuperMine"))
        self.cbx_device.setItemText(0, _translate("MainWindow", "USB device"))
        self.cbx_device.setItemText(1, _translate("MainWindow", "Emulator"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

